# generated by dinoponera — do not edit manually
from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from calc_types.settlement import SettlementParameters, SettlementResult
from calc_types.soil import SoilProfile
from registry.nodes.prompt_soil_profile import prompt_soil_profile
from registry.nodes.prompt_settlement_parameters import prompt_settlement_parameters
from registry.nodes.calculate_settlement import calculate_settlement

def run() -> SettlementResult:
    soil_profile = prompt_soil_profile()
    settlement_parameters = prompt_settlement_parameters()
    settlement_result = calculate_settlement(soil_profile=soil_profile, parameters=settlement_parameters)
    return settlement_result


if __name__ == "__main__":
    result = run()
    print(result)
