# generated by dinoponera — do not edit manually
from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from calc_types.cpt import CptData
from calc_types.piled_foundation import PileFoundationParameters, PileFoundationResult, PileGeometry
from registry.nodes.manual_pile_geometry import manual_pile_geometry
from registry.nodes.hypothetical_cpt_data import hypothetical_cpt_data
from registry.nodes.derive_pile_foundation_parameters_from_cpt import derive_pile_foundation_parameters_from_cpt
from registry.nodes.calculate_pile_foundation_capacity import calculate_pile_foundation_capacity

def run() -> PileFoundationResult:
    pile_geometry = manual_pile_geometry()
    cpt_data = hypothetical_cpt_data()
    pile_foundation_parameters = derive_pile_foundation_parameters_from_cpt(cpt=cpt_data)
    pile_foundation_result = calculate_pile_foundation_capacity(geometry=pile_geometry, parameters=pile_foundation_parameters, cpt=cpt_data)
    return pile_foundation_result


if __name__ == "__main__":
    result = run()
    print(result)
