# generated by dinoponera — do not edit manually
from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from calc_types.example import BaseValue, CalculationResult, DoubledValue
from registry.nodes.example_source_value import example_source_value
from registry.nodes.double_value import double_value
from registry.nodes.format_result import format_result

def run() -> CalculationResult:
    base_value = example_source_value()
    doubled_value = double_value(base=base_value)
    calculation_result = format_result(doubled=doubled_value)
    return calculation_result


if __name__ == "__main__":
    result = run()
    print(result)
