"""Generate standalone Python execution scripts from approved graphs."""

from __future__ import annotations

import argparse
from collections import defaultdict, deque
from pathlib import Path

from dinoponera.core.lint import lint_graph
from dinoponera.core.models import CalculationGraph, NodeSummary
from dinoponera.core.naming import import_path_leaf, to_snake_case
from registry import index as registry_index


class ScriptGenerationError(ValueError):
    """Raised when a graph cannot be converted to a run script."""


def _summary_map(summaries: list[NodeSummary]) -> dict[str, NodeSummary]:
    result: dict[str, NodeSummary] = {}
    for summary in summaries:
        if summary.id in result:
            raise ScriptGenerationError(f"Duplicate node summary id: {summary.id}")
        result[summary.id] = summary
    return result


def topological_sort(graph: CalculationGraph) -> list[str]:
    """Return graph node IDs in producer-before-consumer order."""

    node_set = set(graph.nodes)
    if len(node_set) != len(graph.nodes):
        raise ScriptGenerationError("Graph contains duplicate node IDs")

    adjacency: dict[str, list[str]] = {node_id: [] for node_id in graph.nodes}
    indegree: dict[str, int] = {node_id: 0 for node_id in graph.nodes}

    for edge in graph.edges:
        if edge.from_node not in node_set:
            raise ScriptGenerationError(f"Edge references unknown producer: {edge.from_node}")
        if edge.to_node not in node_set:
            raise ScriptGenerationError(f"Edge references unknown consumer: {edge.to_node}")
        adjacency[edge.from_node].append(edge.to_node)
        indegree[edge.to_node] += 1

    queue = deque(node_id for node_id in graph.nodes if indegree[node_id] == 0)
    ordered: list[str] = []

    while queue:
        node_id = queue.popleft()
        ordered.append(node_id)
        for downstream in adjacency[node_id]:
            indegree[downstream] -= 1
            if indegree[downstream] == 0:
                queue.append(downstream)

    if len(ordered) != len(graph.nodes):
        raise ScriptGenerationError("Graph contains a cycle")
    return ordered


def _split_import_path(import_path: str) -> tuple[str, str]:
    try:
        module, name = import_path.rsplit(".", 1)
    except ValueError as exc:
        raise ScriptGenerationError(f"Invalid import path: {import_path}") from exc
    return module, name


def _type_import_lines(type_paths: set[str]) -> list[str]:
    by_module: dict[str, list[str]] = defaultdict(list)
    for path in sorted(type_paths):
        module, name = _split_import_path(path)
        by_module[module].append(name)
    return [
        f"from {module} import {', '.join(sorted(set(names)))}"
        for module, names in sorted(by_module.items())
    ]


def _node_import_lines(node_ids: list[str]) -> list[str]:
    return [
        f"from {registry_index.get(node_id).__module__} import {node_id}"
        for node_id in node_ids
    ]


def _variable_names(ordered_node_ids: list[str], summary_by_id: dict[str, NodeSummary]) -> dict[str, str]:
    used: set[str] = set()
    result: dict[str, str] = {}
    for node_id in ordered_node_ids:
        base = to_snake_case(import_path_leaf(summary_by_id[node_id].output))
        candidate = base
        if candidate in used:
            candidate = f"{base}_{to_snake_case(node_id)}"
            counter = 2
            while candidate in used:
                candidate = f"{base}_{to_snake_case(node_id)}_{counter}"
                counter += 1
        used.add(candidate)
        result[node_id] = candidate
    return result


def generate_script_source(
    graph: CalculationGraph,
    summaries: list[NodeSummary] | None = None,
) -> str:
    """Render a standalone run script for an approved calculation graph."""

    summaries = summaries if summaries is not None else registry_index.summaries()
    lint_graph(graph, summaries)
    summary_by_id = _summary_map(summaries)

    ordered = topological_sort(graph)
    var_by_node = _variable_names(ordered, summary_by_id)

    type_paths: set[str] = set()
    for node_id in ordered:
        summary = summary_by_id[node_id]
        type_paths.add(summary.output)
        type_paths.update(node_input.type for node_input in summary.inputs)

    edge_by_target: dict[tuple[str, str, str], list[str]] = defaultdict(list)
    for edge in graph.edges:
        edge_by_target[(edge.to_node, edge.to_input, edge.type)].append(edge.from_node)

    lines: list[str] = [
        "# generated by dinoponera — do not edit manually",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "import sys",
        "",
        "sys.path.insert(0, str(Path(__file__).resolve().parents[1]))",
        "",
    ]
    lines.extend(_type_import_lines(type_paths))
    lines.extend(_node_import_lines(ordered))
    lines.append("")
    terminal_type = import_path_leaf(summary_by_id[graph.terminal_node_id].output)
    lines.append(f"def run() -> {terminal_type}:")

    for node_id in ordered:
        summary = summary_by_id[node_id]
        arguments: list[str] = []
        for node_input in summary.inputs:
            matches = edge_by_target[(node_id, node_input.name, node_input.type)]
            if len(matches) != 1:
                raise ScriptGenerationError(
                    f"Node {node_id!r} input {node_input.name!r} expects exactly one "
                    f"edge of type {node_input.type!r}; found {len(matches)}"
                )
            arguments.append(f"{node_input.name}={var_by_node[matches[0]]}")
        call = f"{node_id}({', '.join(arguments)})"
        lines.append(f"    {var_by_node[node_id]} = {call}")

    lines.append(f"    return {var_by_node[graph.terminal_node_id]}")
    lines.extend(
        [
            "",
            "",
            "if __name__ == \"__main__\":",
            "    result = run()",
            "    print(result)",
            "",
        ]
    )
    return "\n".join(lines)


def load_graph(path: str | Path) -> CalculationGraph:
    return CalculationGraph.model_validate_json(Path(path).read_text())


def write_run_script(
    graph: CalculationGraph,
    runs_dir: str | Path = "runs",
    summaries: list[NodeSummary] | None = None,
) -> Path:
    runs_path = Path(runs_dir)
    runs_path.mkdir(parents=True, exist_ok=True)
    output_path = runs_path / f"run_{graph.name}.py"
    output_path.write_text(generate_script_source(graph, summaries=summaries))
    return output_path


def write_run_script_from_graph_path(
    graph_path: str | Path,
    runs_dir: str | Path = "runs",
) -> Path:
    return write_run_script(load_graph(graph_path), runs_dir=runs_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a Dinoponera run script from a graph JSON file.")
    parser.add_argument("graph", help="Path to graphs/{name}.json")
    parser.add_argument("--runs-dir", default="runs", help="Directory for generated run scripts")
    args = parser.parse_args(argv)
    path = write_run_script_from_graph_path(args.graph, runs_dir=args.runs_dir)
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
