# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class BamlCalculationGraph(BaseModel):
    name: typing.Optional[str] = None
    terminal_node_id: typing.Optional[str] = None
    nodes: typing.List[str]
    edges: typing.List["BamlEdge"]

class BamlEdge(BaseModel):
    from_node: typing.Optional[str] = None
    to_node: typing.Optional[str] = None
    to_input: typing.Optional[str] = None
    type: typing.Optional[str] = None

class BamlNodeInput(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None

class BamlNodeSummary(BaseModel):
    id: typing.Optional[str] = None
    node_type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    when_to_use: typing.Optional[str] = None
    assumptions: typing.List[str]
    inputs: typing.List["BamlNodeInput"]
    output: typing.Optional[str] = None
    references: typing.List[str]

class BamlQA(BaseModel):
    question: typing.Optional[str] = None
    answer: typing.Optional[str] = None

class BamlStateSummary(BaseModel):
    goal: typing.Optional[str] = None
    decisions: typing.List[str]
    open_items: typing.List[str]
    phase1_clarification_summary: typing.Optional[str] = None

class BamlUnresolvedInput(BaseModel):
    node_id: typing.Optional[str] = None
    input_name: typing.Optional[str] = None
    input_type: typing.Optional[str] = None

class GoalIdentificationResult(BaseModel):
    kind: typing.Optional[types.GoalIdentificationKind] = None
    calculation_type: typing.Optional[str] = None
    terminal_node_id: typing.Optional[str] = None
    missing_description: typing.Optional[str] = None
    state_summary: typing.Optional["BamlStateSummary"] = None
    question: typing.Optional[str] = None
    context: typing.Optional[str] = None

class GraphExtensionResult(BaseModel):
    kind: typing.Optional[types.GraphExtensionKind] = None
    from_node_id: typing.Optional[str] = None
    node_id: typing.Optional[str] = None
    question: typing.Optional[str] = None
    candidates: typing.Optional[typing.List["BamlNodeSummary"]] = None
    needed_description: typing.Optional[str] = None
    rationale: typing.Optional[str] = None
    updated_state_summary: typing.Optional["BamlStateSummary"] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
