# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BamlCalculationGraph": types.BamlCalculationGraph,
    "stream_types.BamlCalculationGraph": stream_types.BamlCalculationGraph,

    "types.BamlEdge": types.BamlEdge,
    "stream_types.BamlEdge": stream_types.BamlEdge,

    "types.BamlNodeInput": types.BamlNodeInput,
    "stream_types.BamlNodeInput": stream_types.BamlNodeInput,

    "types.BamlNodeSummary": types.BamlNodeSummary,
    "stream_types.BamlNodeSummary": stream_types.BamlNodeSummary,

    "types.BamlQA": types.BamlQA,
    "stream_types.BamlQA": stream_types.BamlQA,

    "types.BamlStateSummary": types.BamlStateSummary,
    "stream_types.BamlStateSummary": stream_types.BamlStateSummary,

    "types.BamlUnresolvedInput": types.BamlUnresolvedInput,
    "stream_types.BamlUnresolvedInput": stream_types.BamlUnresolvedInput,

    "types.GoalIdentificationResult": types.GoalIdentificationResult,
    "stream_types.GoalIdentificationResult": stream_types.GoalIdentificationResult,

    "types.GraphExtensionResult": types.GraphExtensionResult,
    "stream_types.GraphExtensionResult": stream_types.GraphExtensionResult,


    "types.GoalIdentificationKind": types.GoalIdentificationKind,

    "types.GraphExtensionKind": types.GraphExtensionKind,

}