# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class GoalIdentificationKind(str, Enum):
    GoalClear = "GoalClear"
    NeedsClarification = "NeedsClarification"

class GraphExtensionKind(str, Enum):
    ConnectExisting = "ConnectExisting"
    AddFromRegistry = "AddFromRegistry"
    ApplicabilityCheck = "ApplicabilityCheck"
    NoCandidate = "NoCandidate"

# #########################################################################
# Generated classes (9)
# #########################################################################

class BamlCalculationGraph(BaseModel):
    name: str
    terminal_node_id: str
    nodes: typing.List[str]
    edges: typing.List["BamlEdge"]

class BamlEdge(BaseModel):
    from_node: str
    to_node: str
    to_input: str
    type: str

class BamlNodeInput(BaseModel):
    name: str
    type: str

class BamlNodeSummary(BaseModel):
    id: str
    node_type: str
    description: str
    when_to_use: str
    assumptions: typing.List[str]
    inputs: typing.List["BamlNodeInput"]
    output: str
    references: typing.List[str]

class BamlQA(BaseModel):
    question: str
    answer: str

class BamlStateSummary(BaseModel):
    goal: str
    decisions: typing.List[str]
    open_items: typing.List[str]
    phase1_clarification_summary: str

class BamlUnresolvedInput(BaseModel):
    node_id: str
    input_name: str
    input_type: str

class GoalIdentificationResult(BaseModel):
    kind: GoalIdentificationKind
    calculation_type: typing.Optional[str] = None
    terminal_node_id: typing.Optional[str] = None
    missing_description: typing.Optional[str] = None
    state_summary: typing.Optional["BamlStateSummary"] = None
    question: typing.Optional[str] = None
    context: typing.Optional[str] = None

class GraphExtensionResult(BaseModel):
    kind: GraphExtensionKind
    from_node_id: typing.Optional[str] = None
    node_id: typing.Optional[str] = None
    question: typing.Optional[str] = None
    candidates: typing.Optional[typing.List["BamlNodeSummary"]] = None
    needed_description: typing.Optional[str] = None
    rationale: typing.Optional[str] = None
    updated_state_summary: typing.Optional["BamlStateSummary"] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
